PCA: |
  # Execute script data to get memory usage
  if __name__ == "__main__":
      # For reproducibility
      np.random.seed(42)
  
      # Generate random data
      data = np.random.rand(10000, 100)
      
      # Create PCA object
      pca = PrincipalComponentAnalysis()
  
      # Fit and transform data
      pca.fit(data)
      _ = pca.transform(data)
      
      # Get the CPU percentage usage of the process
      cpu_usage = process.cpu_percent(interval=1)/ num_cores
      print(f"CPU Usage: {cpu_usage}%")


attention: |
  <write execution script for attention>

convolution: |
  <write execution script for convolution>

gemm: |
  <write execution script for gemm>

huffman: |
  <write execution script for huffman>

monte_carlo_simulation: |
  <write execution script for monte_carlo>

page_rank: |
  <write execution script for page_rank>

quick_sort: |
  <write execution script for quick_sort>

rabin-karp: |
  <write execution script for rabin-karp>